# Generated by Django 5.2 on 2025-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=6)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "employer_ticket_contrib",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "actual_salary_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("actual_tickets_received", models.IntegerField(blank=True, null=True)),
                (
                    "actual_gratification_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
